[project]
name = "exam3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "pillow>=11.0.0",
    "pydantic-ai-slim[openai]>=1.9.1",
    "python-dotenv>=1.2.1",
]
